import Joi from 'joi';

export const ClientCreateSchema = Joi.object({
	code: Joi.alternatives().try(Joi.string().trim(), Joi.number()).label('Code').required(),
	email: Joi.string().trim().allow('', null).label('Email'),
	name: Joi.string().trim().label('Client Name').required(),
	country: Joi.string().trim().label('Country').required(),
	timezone: Joi.string().trim().label('Timezone').required(),
	currency: Joi.string().trim().label('Currency').allow('', null),
	weekendDays: Joi.string().trim().allow('', null).label('Weekend Days'),
	isAllDays: Joi.boolean().default(false),
	isActive: Joi.boolean().default(true),
	startDate: Joi.date().label('Start Date').required(),
	endDate: Joi.date().label('End Date').required(),
	autoUpdateEndDate: Joi.number().label('Auto Update End Date'),
	timeSheetStartDay: Joi.number().label('Timesheet Start Day').default(1).required(),
	approvalEmail: Joi.array().items(Joi.string().label('Approval Email')),
	isShowPrices: Joi.boolean().default(false).label('Show Prices'),
	isShowCostCenter: Joi.boolean().default(false).label('Show Cost Center'),
	isShowCatalogueNo: Joi.boolean().default(false).label('Show Catalogue No'),
	titreDeConge: Joi.array().items(Joi.string().label('Titre De Conge')),
	isResetBalance: Joi.boolean().default(false).label('Reset Balance'),
	startMonthBack: Joi.number().label('Start Month Back').default(0).required(),
	medicalEmailSubmission: Joi.array().items(Joi.string().label('Medical Email Submission')),
	medicalEmailToday: Joi.array().items(Joi.string().label('Medical Email Today')),
	medicalEmailMonthly: Joi.array().items(Joi.string().label('Medical Email Monthly')),
	isShowNSS: Joi.boolean().default(false).label('Show NSS'),
	isShowCarteChifa: Joi.boolean().default(false).label('Show Carte Chifa'),
	isShowSalaryInfo: Joi.boolean().default(false).label('Show Salary Info'),
	isShowRotation: Joi.boolean().default(false).label('Show Rotation'),
	isShowBalance: Joi.boolean().default(false).label('Show Balance'),
	logo: Joi.any().label('Logo'),
	segment: Joi.string().trim().allow('', null).label('Segment'),
	subSegment: Joi.string().trim().allow('', null).label('Sub Segment'),
	bonusType: Joi.string().trim().allow('', null).label('Bonus Type'),
	isCountCR: Joi.boolean().default(false).label('Count CR'),
	contractN: Joi.string().trim().allow('', null).label('N'),
	stampLogo: Joi.any().label('Logo').allow('', null),
	contractTagline: Joi.string().trim().allow('', null).label('Tagline'),
	address: Joi.string().trim().allow('', null).label('Address'),
}).options({
	abortEarly: false,
});

export const ClientUpdateSchema = Joi.object({
	code: Joi.alternatives().try(Joi.string().trim(), Joi.number()).label('Code'),
	email: Joi.string().trim().allow('', null).label('Email'),
	name: Joi.string().trim().label('Client Name'),
	country: Joi.string().trim().label('Country'),
	stampLogo: Joi.any().label('Logo').allow('', null),
	timezone: Joi.string().trim().label('timezone').required(),
	currency: Joi.string().trim().label('Currency').allow('', null),
	weekendDays: Joi.string().trim().allow('', null).label('Weekend Days'),
	isAllDays: Joi.boolean().default(false),
	isActive: Joi.boolean(),
	startDate: Joi.date().label('Start Date'),
	endDate: Joi.date().label('End Date'),
	autoUpdateEndDate: Joi.number().label('Auto Update End Date'),
	timeSheetStartDay: Joi.number().label('Timesheet Start Day'),
	approvalEmail: Joi.array().items(Joi.string().label('Approval Email')),
	isShowPrices: Joi.boolean().label('Show Prices'),
	isShowCostCenter: Joi.boolean().label('Show Cost Center'),
	isShowCatalogueNo: Joi.boolean().label('Show Catalogue No'),
	titreDeConge: Joi.array().items(Joi.string().label('Titre De Conge')),
	isResetBalance: Joi.boolean().label('Reset Balance'),
	startMonthBack: Joi.number().label('Start Month Back'),
	medicalEmailSubmission: Joi.array().items(Joi.string().label('Medical Email Submission')),
	medicalEmailToday: Joi.array().items(Joi.string().label('Medical Email Today')),
	medicalEmailMonthly: Joi.array().items(Joi.string().label('Medical Email Monthly')),
	isShowNSS: Joi.boolean().label('Show NSS'),
	isShowCarteChifa: Joi.boolean().label('Show Carte Chifa'),
	isShowSalaryInfo: Joi.boolean().label('Show Salary Info'),
	isShowRotation: Joi.boolean().label('Show Rotation'),
	isShowBalance: Joi.boolean().label('Show Balance'),
	logo: Joi.any().label('Logo'),
	segment: Joi.string().trim().allow('', null).label('Segment'),
	subSegment: Joi.string().trim().allow('', null).label('Sub Segment'),
	bonusType: Joi.string().trim().allow('', null).label('Bonus Type'),
	isCountCR: Joi.boolean().default(false).label('Count CR'),
	contractN: Joi.string().trim().allow('', null).label('N'),
	contractTagline: Joi.string().trim().allow('', null).label('Tagline'),
	address: Joi.string().trim().allow('', null).label('Address'),
}).options({
	abortEarly: false,
});

export const ClientStatusUpdateSchema = Joi.object({
	isActive: Joi.boolean().required(),
}).options({
	abortEarly: false,
});
